DROP TABLE IF EXISTS Best_Original_Song CASCADE;
DROP TABLE IF EXISTS Best_Adapted_Screenplay CASCADE;
DROP TABLE IF EXISTS Best_International_Picture CASCADE;
DROP TABLE IF EXISTS Best_Documental CASCADE;
DROP TABLE IF EXISTS Best_Visual_Effects CASCADE;
DROP TABLE IF EXISTS Best_Sound CASCADE;
DROP TABLE IF EXISTS Best_Editing CASCADE;
DROP TABLE IF EXISTS Best_Production_Design CASCADE;
DROP TABLE IF EXISTS Best_Actor_Supporting CASCADE;
DROP TABLE IF EXISTS Best_Actress_Supporting CASCADE;
DROP TABLE IF EXISTS Best_Actor CASCADE;
DROP TABLE IF EXISTS Best_Actress CASCADE;
DROP TABLE IF EXISTS Best_Original_Song CASCADE;
DROP TABLE IF EXISTS Best_Director CASCADE;
DROP TABLE IF EXISTS Best_Picture CASCADE;


create table Best_Original_Song (
    Year INT primary key,
    Title VARCHAR(255),
    Movie VARCHAR(255),
    Composer VARCHAR(255)
);